/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameoflife;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author willne763
 */
@SuppressWarnings("ALL")
@Deprecated
public class OldGameOfLifeFrame
        extends javax.swing.JFrame{
    
    /**
     * Creates new form OldGameOfLifeFrame
     */
    public OldGameOfLifeFrame(){
        model = new DefaultComboBoxModel<>(BoardTypes.values());
        initComponents();
        int delay=100;
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                boardPanel.iterate();
                jLabelIter.setText(Integer.toString(boardPanel.getIterations()));
            }  
        };
        timer = new Timer(delay, listener);
        timer.stop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelIter = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<BoardTypes>();
        boardPanel = new gameoflife.BoardPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemClear = new javax.swing.JMenuItem();
        jMenuEditColor = new javax.swing.JMenu();
        jMenuItemRed = new javax.swing.JMenuItem();
        jMenuItemBlue = new javax.swing.JMenuItem();
        jMenuItemGreen = new javax.swing.JMenuItem();
        jMenuItemBlack = new javax.swing.JMenuItem();
        jMenuItemRandomColor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(740, 730));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setText("Iterations:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel1);

        jLabelIter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIter.setText("0");
        jLabelIter.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabelIter);

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jSlider1.setMaximum(200);
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel2.add(jSlider1);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jLabel3.setText("<- Speed");
        jPanel3.add(jLabel3);

        jComboBox1.setModel(model);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);

        jPanel2.add(jPanel3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        boardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boardPanelMouseClicked(evt);
            }
        });
        getContentPane().add(boardPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenuEdit.setText("Edit");

        jMenuItemClear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.META_MASK));
        jMenuItemClear.setText("Clear WrapAroundBoard");
        jMenuItemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClearActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemClear);

        jMenuEditColor.setText("Set Cell Color");

        jMenuItemRed.setText("Red");
        jMenuItemRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRedActionPerformed(evt);
            }
        });
        jMenuEditColor.add(jMenuItemRed);

        jMenuItemBlue.setText("Blue");
        jMenuItemBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBlueActionPerformed(evt);
            }
        });
        jMenuEditColor.add(jMenuItemBlue);

        jMenuItemGreen.setText("Green");
        jMenuItemGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGreenActionPerformed(evt);
            }
        });
        jMenuEditColor.add(jMenuItemGreen);

        jMenuItemBlack.setText("Black");
        jMenuItemBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBlackActionPerformed(evt);
            }
        });
        jMenuEditColor.add(jMenuItemBlack);

        jMenuItemRandomColor.setText("Random");
        jMenuItemRandomColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRandomColorActionPerformed(evt);
            }
        });
        jMenuEditColor.add(jMenuItemRandomColor);

        jMenuEdit.add(jMenuEditColor);

        jMenuBar1.add(jMenuEdit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        if(!jSlider1.getValueIsAdjusting()){
            if(!(jSlider1.getValue()==0)){
                timer.setDelay(10000 / jSlider1.getValue());
                timer.start();
            } else {
                timer.stop();
            }
        }
    }//GEN-LAST:event_jSlider1StateChanged

    private void jMenuItemClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClearActionPerformed
        boardPanel.clear();
        jLabelIter.setText("0");
    }//GEN-LAST:event_jMenuItemClearActionPerformed

    private void boardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardPanelMouseClicked
        boardPanel.clicked(evt);
        jLabelIter.setText("0");
    }//GEN-LAST:event_boardPanelMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        boardPanel.setBoard((BoardTypes) jComboBox1.getSelectedItem());
        jLabelIter.setText("0");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenuItemRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRedActionPerformed
        boardPanel.setSelectedColor(Color.RED);
        boardPanel.repaint();
    }//GEN-LAST:event_jMenuItemRedActionPerformed

    private void jMenuItemBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBlueActionPerformed
        boardPanel.setSelectedColor(Color.BLUE);
        boardPanel.repaint();
    }//GEN-LAST:event_jMenuItemBlueActionPerformed

    private void jMenuItemGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGreenActionPerformed
        boardPanel.setSelectedColor(Color.GREEN);
        boardPanel.repaint();
    }//GEN-LAST:event_jMenuItemGreenActionPerformed

    private void jMenuItemBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBlackActionPerformed
        boardPanel.setSelectedColor(Color.BLACK);
        boardPanel.repaint();
    }//GEN-LAST:event_jMenuItemBlackActionPerformed

    private void jMenuItemRandomColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRandomColorActionPerformed
        boardPanel.setSelectedColor(new Color(
                (int)(Math.random()*155)+100,
                (int)(Math.random()*155)+100,
                (int)(Math.random()*155)+100
        ));
        boardPanel.repaint();
    }//GEN-LAST:event_jMenuItemRandomColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                System.setProperty("apple.laf.useScreenMenuBar", "true");
                //noinspection deprecation
                new OldGameOfLifeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gameoflife.BoardPanel boardPanel;
    private javax.swing.JComboBox<BoardTypes> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelIter;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuEditColor;
    private javax.swing.JMenuItem jMenuItemBlack;
    private javax.swing.JMenuItem jMenuItemBlue;
    private javax.swing.JMenuItem jMenuItemClear;
    private javax.swing.JMenuItem jMenuItemGreen;
    private javax.swing.JMenuItem jMenuItemRandomColor;
    private javax.swing.JMenuItem jMenuItemRed;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
    private Timer timer;
    private DefaultComboBoxModel<BoardTypes> model;
}
